# Define the conda python environment
name: py_kafka
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - python-dotenv
  - pyyaml
  - uvicorn
  - httpie
  - beautifulsoup4
  - python-confluent-kafka
  - fastavro
  - aiohttp
  - pymongo
  - pip
  - pip:
    - openai
    - apache-airflow
    - apache-airflow-providers-apache-kafka==1.1.2
    - apache-airflow-providers-telegram==4.1.1
    - apache-airflow-providers-mongo==3.2.1S
